import { Market, Analysis, SubscriptionPlan, Price } from '@/lib/types';

export const mockMarkets: Market[] = [
  {
    id: '1',
    name: 'بورس ایران',
    slug: 'iran-stocks',
    symbol: 'شاخص کل',
    icon: '📊',
    description: 'رصد بورس تهران، صنایع پیشرو و نمادهای اثرگذار بازار سهام ایران',
  },
  {
    id: '2',
    name: 'فارکس',
    slug: 'forex',
    symbol: 'جفت‌ارزها',
    icon: '💱',
    description: 'تحلیل جفت‌ارزهای اصلی، روند دلار جهانی و فرصت‌های کوتاه‌مدت',
  },
  {
    id: '3',
    name: 'طلا',
    slug: 'gold',
    symbol: 'اونس جهانی',
    icon: '🏆',
    description: 'ردیابی قیمت نقدی طلا، فلزات گران‌بها و سطوح کلیدی بازار',
  },
  {
    id: '4',
    name: 'ارز',
    slug: 'currency',
    symbol: 'دلار/ریال',
    icon: '💵',
    description: 'پیگیری دلار، یورو و سبد ارزهای مهم در برابر ریال ایران',
  },
];

// Mock Analyses Data
export const mockAnalyses: Analysis[] = [
  {
    id: '1',
    marketId: '1',
    title: 'شتاب صعودی در گروه فناوری',
    summary: 'نمادهای فناوری با پشتوانه بنیادی و جریان پول مثبت در حال تقویت هستند',
    fullContent:
      'گروه فناوری در بازار ایران همچنان ظرفیت رشد مطلوبی نشان می‌دهد و بازیگران اصلی فراتر از انتظار بازار عمل کرده‌اند. سطوح حمایتی کلیدی حفظ شده‌اند.',
    timeframe: 'monthly',
    analysisType: 'long_term',
    signal: 'BUY',
    riskLevel: 'MEDIUM',
    targetPrice: 1850,
    entryPrice: 1620,
    stopLoss: 1550,
    takeProfit: 2100,
    accuracy: 78.5,
    publishedAt: new Date('2026-06-04'),
    isLocked: false,
    requiredSubscription: undefined,
  },
  {
    id: '2',
    marketId: '2',
    title: 'الگوی تراکم یورو/دلار',
    summary: 'قیمت نزدیک مقاومت کلیدی فشرده شده و شکست معتبر اهمیت دارد',
    fullContent: 'یورو/دلار در محدوده‌ای فشرده نوسان می‌کند. شکست سطح ۱.۱۲۵۰ می‌تواند مسیر رشد تا ۱.۱۴۰۰ را باز کند.',
    timeframe: 'weekly',
    analysisType: 'short_term',
    signal: 'HOLD',
    riskLevel: 'LOW',
    targetPrice: 1.125,
    entryPrice: 1.102,
    stopLoss: 1.095,
    takeProfit: 1.14,
    accuracy: 82.3,
    publishedAt: new Date('2026-06-05'),
    isLocked: true,
    requiredSubscription: 'weekly',
  },
  {
    id: '3',
    marketId: '3',
    title: 'شکست صعودی طلا',
    summary: 'طلا با عبور از مقاومت کلیدی، سناریوی صعودی تازه‌ای ساخته است',
    fullContent: 'طلا بالاتر از مقاومت مهم ۲۴۰۰ دلار تثبیت شده و نشانه‌ای از ادامه حرکت صعودی قدرتمند دارد.',
    timeframe: 'daily',
    analysisType: 'short_term',
    signal: 'BUY',
    riskLevel: 'MEDIUM',
    targetPrice: 2500,
    entryPrice: 2410,
    stopLoss: 2380,
    takeProfit: 2580,
    accuracy: 75,
    publishedAt: new Date('2026-06-05'),
    isLocked: false,
  },
];

// Mock Subscription Plans
export const mockSubscriptionPlans: SubscriptionPlan[] = [
  {
    id: '1',
    name: 'تحلیل روزانه',
    slug: 'daily-analysis',
    description: 'تحلیل روزانه بازار برای معامله‌گران کوتاه‌مدت',
    type: 'timeframe',
    price: 49,
    currency: 'USD',
    billingPeriod: 'monthly',
    features: ['تحلیل روزانه', 'دسترسی به یک بازار', 'هشدارهای پایه', 'اعلان ایمیلی'],
    isActive: true,
  },
  {
    id: '2',
    name: 'تحلیل هفتگی',
    slug: 'weekly-analysis',
    description: 'تحلیل عمیق هفتگی برای معامله‌گران نوسانی',
    type: 'timeframe',
    price: 99,
    currency: 'USD',
    billingPeriod: 'monthly',
    features: ['تحلیل هفتگی', 'تمام تایم‌فریم‌های کوتاه‌مدت', 'هشدارهای پیشرفته', 'پشتیبانی اولویت‌دار'],
    isActive: true,
  },
  {
    id: '3',
    name: 'تحلیل ماهانه',
    slug: 'monthly-analysis',
    description: 'تحلیل استراتژیک ماهانه برای سرمایه‌گذاران فعال',
    type: 'timeframe',
    price: 149,
    currency: 'USD',
    billingPeriod: 'monthly',
    features: ['تحلیل ماهانه', 'گزارش‌های دقیق', 'راهنمایی پورتفو', 'مشاور اختصاصی'],
    isActive: true,
  },
  {
    id: '4',
    name: 'استراتژی سه‌ماهه',
    slug: '3month-strategic',
    description: 'تحلیل استراتژیک بلندمدت به‌صورت فصلی',
    type: 'long_term',
    price: 299,
    currency: 'USD',
    billingPeriod: 'quarterly',
    features: ['گزارش فصلی', 'تحلیل روند', 'ارزیابی ریسک', 'راهنمایی بازچینی'],
    isActive: true,
  },
  {
    id: '5',
    name: 'پورتفوی یک‌ساله',
    slug: '1year-portfolio',
    description: 'مدیریت جامع پورتفو در افق یک‌ساله',
    type: 'long_term',
    price: 999,
    currency: 'USD',
    billingPeriod: 'yearly',
    features: ['استراتژی سالانه', 'بازچینی فصلی', 'ارتباط مستقیم با مشاور', 'دسترسی کامل بازار'],
    isActive: true,
  },
  {
    id: '6',
    name: 'ثروت VIP سه‌ساله',
    slug: '3year-vip',
    description: 'استراتژی مدیریت ثروت در افق بلندمدت',
    type: 'long_term',
    price: 2499,
    currency: 'USD',
    billingPeriod: 'yearly',
    features: ['برنامه استراتژیک سه‌ساله', 'بازبینی ماهانه پورتفو', 'تحلیل اولویت‌دار VIP', 'دسترسی کامل بازار'],
    isActive: true,
  },
  {
    id: '7',
    name: 'دسترسی کامل یک بازار',
    slug: 'market-full',
    description: 'دسترسی کامل به تحلیل‌ها و سیگنال‌های یک بازار مشخص',
    type: 'market_full',
    price: 399,
    currency: 'USD',
    billingPeriod: 'monthly',
    features: ['تمام تایم‌فریم‌های یک بازار', 'سیگنال‌های اختصاصی', 'هشدار لحظه‌ای', 'داده تاریخی'],
    isActive: true,
  },
  {
    id: '8',
    name: 'دسترسی همه بازارها',
    slug: 'all-markets',
    description: 'دسترسی پریمیوم به همه بازارهای فعال پلتفرم',
    type: 'all_markets',
    price: 699,
    currency: 'USD',
    billingPeriod: 'monthly',
    features: ['دسترسی کامل همه بازارها', 'تمام انواع تحلیل', 'هشدار چنددارایی', 'پشتیبانی اولویت‌دار'],
    isActive: true,
  },
  {
    id: '9',
    name: 'VIP الیت',
    slug: 'vip-elite',
    description: 'تجربه کامل مشاوره اختصاصی سرمایه‌گذاری',
    type: 'vip',
    price: 1299,
    currency: 'USD',
    billingPeriod: 'monthly',
    features: [
      'مشاور شخصی تمام‌وقت',
      'سیگنال‌های اختصاصی سرمایه‌گذاری',
      'وبینارهای خصوصی بازار',
      'گزارش‌های اختصاصی آلفا',
      'ابزارهای پیشرفته مدیریت ریسک',
      'هشدار قیمت بدون تاخیر',
    ],
    isActive: true,
  },
];

// Mock Price Data
export const mockPrices: Price[] = [
  {
    id: '1',
    symbol: 'TEPIX',
    currentPrice: 1850.25,
    previousClose: 1820.5,
    dayHigh: 1865.0,
    dayLow: 1815.0,
    volume: 2500000,
    marketCap: 450000000000,
    change: 29.75,
    changePercent: 0.0163,
    timestamp: new Date(),
  },
  {
    id: '2',
    symbol: 'EUR/USD',
    currentPrice: 1.0945,
    previousClose: 1.0920,
    dayHigh: 1.0980,
    dayLow: 1.0910,
    volume: 150000,
    change: 0.0025,
    changePercent: 0.0023,
    timestamp: new Date(),
  },
  {
    id: '3',
    symbol: 'XAU/USD',
    currentPrice: 2438.5,
    previousClose: 2410.0,
    dayHigh: 2445.0,
    dayLow: 2405.0,
    volume: 500000,
    change: 28.5,
    changePercent: 0.0118,
    timestamp: new Date(),
  },
  {
    id: '4',
    symbol: 'USD/IRR',
    currentPrice: 42650,
    previousClose: 42500,
    dayHigh: 42750,
    dayLow: 42400,
    volume: 1000000,
    change: 150,
    changePercent: 0.0035,
    timestamp: new Date(),
  },
];

// Market Summary Data
export const marketSummary = {
  totalMarkets: 4,
  activeAnalyses: 15,
  totalSubscribers: 5230,
  marketIndices: [
    { name: 'شاخص بازار ایران', value: 1850, change: 1.63, trend: 'up' as const },
    { name: 'میانگین فارکس', value: 1.0945, change: 0.23, trend: 'up' as const },
    { name: 'شاخص طلا', value: 2438.5, change: 1.18, trend: 'up' as const },
    { name: 'سبد ارز', value: 42650, change: 0.35, trend: 'up' as const },
  ],
};

// Performance Stats
export const performanceStats = {
  accuracy: 78.5,
  wins: 156,
  losses: 42,
  winRate: 78.79,
  averageReturn: 2.45,
  totalAnalyses: 198,
};
